[versions]
agp = "8.9.2"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.05.00"
googleServices = "4.4.2"
firebaseBom = "33.13.0"
coil = "3.1.0"
lottie = "6.6.6"
datastorePreferences = "1.1.6"
navigation = "2.9.0"
googleMaps = "2.11.4"
playServicesMaps = "19.2.0"
playServicesAuth = "21.3.0"
kotlinxSerilization = "1.8.1"
permissions = "0.28.0"
location = "21.3.0"
firebaseMLInterpreter = "22.0.4"
firebaseMLModelDwonloader = "25.0.1"
tensorflowLite = "2.9.0"
tensorflowLiteTaskVision = "0.3.1"
tensorflowLiteGPU = "2.9.0"
ktor = "2.3.4"
coroutines = "1.10.1"
lifecycle = "2.6.2"
logback_version = "1.5.6"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebaseMLInterpreter = { group = "com.google.firebase", name = "firebase-ml-model-interpreter", version.ref = "firebaseMLInterpreter" }
firebaseMLModelDwonloader = { group = "com.google.firebase", name = "firebase-ml-modeldownloader", version.ref = "firebaseMLModelDwonloader" }

tensoflowLite = { group = "org.tensorflow", name = "tensorflow-lite", version.ref = "tensorflowLite" }
tensorflowLiteTaskVision = { group = "org.tensorflow", name = "tensorflow-lite-task-vision", version.ref = "tensorflowLiteGPU" }
tensorflowLiteGPU = { group = "org.tensorflow", name = "tensorflow-lite-gpu", version.ref = "tensorflowLiteGPU" }

google-signin = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "playServicesAuth" }
location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "location" }
permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "permissions" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coilNetworkOkHttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coilSvg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

datastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastorePreferences" }

navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

googleMaps = { group = "com.google.maps.android", name = "maps-compose", version.ref = "googleMaps" }
playServicesMaps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }

kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerilization" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-logger = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback_version" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
